# Generated by Django 4.1.5 on 2023-02-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("MobileNumber", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeviceName", models.CharField(max_length=100)),
                ("DeviceType", models.CharField(max_length=100)),
                ("DeviceCost", models.IntegerField()),
                ("Allocated", models.BooleanField(default=False)),
                (
                    "EmployeeAssigned",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="employeeApp.employeedetails",
                    ),
                ),
            ],
        ),
    ]
