# Generated by Django 4.1.5 on 2023-02-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedetails",
            name="EmployeeAssigned",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employeeApp.employeedetails",
            ),
        ),
    ]
