# Generated by Django 4.1.5 on 2023-01-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0003_devicerights"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicerights", old_name="Device_id", new_name="Device",
        ),
        migrations.RenameField(
            model_name="devicerights", old_name="Employee_id", new_name="Employee",
        ),
    ]
