# Generated by Django 4.1.5 on 2023-02-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0005_rename_firstname_employee_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="EmployeeAssigned",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="employee",
                to="employeeApp.employee",
            ),
        ),
    ]
